### ISSUE TITLE
sending on OSX doesn't work

### ISSUE THREAD

**Issue by Lime2K** [DragonMinded/netboot#6] opened 2021-10-30 00:19 UTC
The send starts, and then crashes at the 004000 with a pipeline lost error. From what I can see it's because when the transfer starts the naomi reboots, and the send loses the connection during that reboot. Would it be possible to add a 10-second delay between the reboot command and the start of the send operation to help alleviate this issue?

**Comment by DragonMinded** [comment] 2021-10-31 15:47
Its bizarre that this fails on OSX when the timeout works fine on Linux. I guess OSX has different behavior regarding socket timeouts?

**Comment by itslemcy** [comment] 2021-11-02 21:26
i can confirm this bizzarre issue on both my os x laptops

**Comment by DragonMinded** [comment] 2021-11-02 21:46
We can definitely try putting a sleep in the code. I even have a comment here for where to add one: https://github.com/DragonMinded/netboot/blob/trunk/netdimm/netdimm.py#L136

Aside, if you run netdimm_send with `--disable-now-loading` does it work properly? If that works but sending normally doesn't, then its for sure a sleep issue.

**Comment by itslemcy** [comment] 2021-11-03 10:11
Hi, here is a screenshot of what's happening with --disable-now-loading

![image](https://user-images.githubusercontent.com/7327888/140041896-62ba1ec8-9d6b-4c6a-9cb8-3dbe043403c7.png)

i even tried implementing the sleep(5) or (10) function and this is what i get:

![image](https://user-images.githubusercontent.com/7327888/140042121-ac9d7297-d05e-48ab-8724-1765f5eb5ba1.png)

**Comment by DragonMinded** [comment] 2021-11-03 17:33
What is the deal with OSX in this case? I have no idea what's different between the old scripts and mine functionalitywise, except maybe that setting a timeout at all is bad on OSX?

**Comment by ArcadeHustle** [comment] 2022-01-14 23:19
I got here from https://github.com/DragonMinded/netboot/issues/1

Edited: Anyone on OSX that is flat out unable to use this codebase at all, try to just kill the timeouts. Seems to work fine for me to enable some base functionality. Caveat, please be aware that this does not imply the rest of this repo magically works for you now. You are likely going to have issues with other tools, including the web interface and netdimm_ensure, as pointed out below. 
 
```diff --git a/netdimm/netdimm.py b/netdimm/netdimm.py
index 9cf0e6d..0dd1264 100644
--- a/netdimm/netdimm.py
+++ b/netdimm/netdimm.py
@@ -280,9 +280,7 @@ class NetDimm:
         # - pre-type3 triforces jumpered to satellite mode.
         try:
             self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
-            self.sock.settimeout(1)
             self.sock.connect((self.ip, 10703))
-            self.sock.settimeout(10)
         except Exception as e:
             raise NetDimmException("Could not connect to NetDimm") from e
```

**Comment by DragonMinded** [comment] 2022-01-15 00:15
Woah, before you recommend just nuking lines of code lets work out if this has any other unintended side-effects. Those lines are there for a very good reason, and its to allow the state machine that uses this class to operate properly. Breaking that breaks several tools in this repo, including netdimm_ensure and the entire web interface.

**Comment by ArcadeHustle** [comment] 2022-01-15 00:26
Sorry, that was more of a "hey folks that are having problems, try this, see if you are able to send". For me it was the difference between using the tool at all, vs not. Anyone with this issue is unlikely to be enjoying your web interface at all.

**Comment by DragonMinded** [comment] 2022-01-15 02:11
This repository is far more than just "netdimm_send", the vast majority of the tools here require there to be a correct timeout. As it stands, I tested this and it indeed hangs indefinitely if you turn off power to the cabinet while sending on Linux, only timing out when the cabinet is turned back on again. So, its not a workable solution.

**Comment by DragonMinded** [comment] 2022-02-01 16:49
I'm fairly sure this is fixed with the PR @ArcadeHustle submitted so I'm going to close this task and make a release shortly.

**Closed as completed by DragonMinded** 2022-02-01 16:49 UTC
