### ISSUE TITLE
[Errno 32] Broken pipe received when trying to load game via netdimm_send

### ISSUE THREAD

**Issue by shundi12** [DragonMinded/netboot#1] opened 2020-05-04 01:08 UTC
I have the following setup that is tested with the older Python 2 script:
A Sega Naomi (4.02 firmware) connected to a MacBook Pro with Catalina running Python 2.7 (for the older script) and Python 3.6.8 via a cross over cable.

I ran the following command to attempt to send a game to the Sega Naomi:

netboot id$ python3 -m scripts.netdimm_send 192.168.0.50 powerstone2.bin

This is what is displayed in the terminal window after running the command above:

sending...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/id/Documents/Old Hard drive Backup/Projects/Sega Naomi/Modern_NetBoot/netboot/scripts/netdimm_send.py", line 90, in <module>
    sys.exit(main())
  File "/Users/id/Documents/Old Hard drive Backup/Projects/Sega Naomi/Modern_NetBoot/netboot/scripts/netdimm_send.py", line 81, in main
    netdimm.send(data, key)
  File "/Users/id/Documents/Old Hard drive Backup/Projects/Sega Naomi/Modern_NetBoot/netboot/netboot/netboot.py", line 61, in send
    self.__upload_file(data, key, progress_callback or (lambda _cur, _tot: None))
  File "/Users/id/Documents/Old Hard drive Backup/Projects/Sega Naomi/Modern_NetBoot/netboot/netboot/netboot.py", line 161, in __upload_file
    self.__upload(addr, current, 0)
  File "/Users/id/Documents/Old Hard drive Backup/Projects/Sega Naomi/Modern_NetBoot/netboot/netboot/netboot.py", line 132, in __upload
    self.__write(struct.pack("<IIIH", 0x04800000 | (len(data) + 0xA) | (mark << 16), 0, addr, 0) + data)
  File "/Users/id/Documents/Old Hard drive Backup/Projects/Sega Naomi/Modern_NetBoot/netboot/netboot/netboot.py", line 96, in __write
    self.sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
Ians-MacBook-Pro:netbootid$

**Comment by DragonMinded** [comment] 2020-05-04 01:18
Bizarre, it seems to at least get past the bit where it resets the netdimm to say "Now loading..." and send the key. Does it print out a percentage at all or does it fail right away?

**Comment by DragonMinded** [comment] 2021-10-06 06:28
Closing as I cannot reproduce this issue and its been about a year and a half since last comment.

**Closed as completed by DragonMinded** 2021-10-06 06:28 UTC

**Comment by Lime2K** [comment] 2021-10-30 00:21
I didn't see this before I opened a new issue, but this is the same problem I'm having.

**Comment by ArcadeHustle** [comment] 2022-01-14 23:19
Try yanking the timeouts as a means to get some functionality as opposed to being unable to use this repo. Please be aware this is only known to "fix" netdimm_send in the following use case:
```
python3 ./netdimm_send 192.168.1.121  ../netboot/TheTypingOfTheDead.bin 
``` 
The below will break other things like netdimm_ensure, and likely the web interface. 
```
index 9cf0e6d..0dd1264 100644
--- a/netdimm/netdimm.py
+++ b/netdimm/netdimm.py
@@ -280,9 +280,7 @@ class NetDimm:
         # - pre-type3 triforces jumpered to satellite mode.
         try:
             self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
-            self.sock.settimeout(1)
             self.sock.connect((self.ip, 10703))
-            self.sock.settimeout(10)
         except Exception as e:
             raise NetDimmException("Could not connect to NetDimm") from e
```
